version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./sites-available:/etc/nginx/sites-available
      - ./conf.d:/etc/nginx/conf.d