service: naked-redirect-server
image: narralabs/naked-redirect-server
servers:
  web:
    - 178.156.158.177
proxy:
  ssl: true
  hosts:
    - setoutpost.com
    - toogoodhr.com
registry:
  username: narralabs
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
